# Generated by Django 4.0.3 on 2023-06-01 22:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company_description",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_employees",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_industry",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_investment",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_valuation",
        ),
        migrations.RemoveField(
            model_name="user",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="user",
            name="meeting_link",
        ),
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="position",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meeting_link", models.CharField(max_length=20, null=True)),
                ("position", models.CharField(max_length=20, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "company_photo",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("company_name", models.CharField(max_length=20, null=True)),
                ("company_description", models.CharField(max_length=50, null=True)),
                ("company_valuation", models.CharField(max_length=20, null=True)),
                ("company_employees", models.CharField(max_length=20, null=True)),
                ("company_investment", models.CharField(max_length=20, null=True)),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("startup", "Startup"),
                            ("corporation", "Corporation"),
                        ],
                        default="startup",
                        max_length=20,
                    ),
                ),
                (
                    "company_industry",
                    models.CharField(
                        choices=[
                            ("agriculture", "Agriculture"),
                            ("construction", "Construction"),
                            ("education", "Education"),
                            ("energy", "Energy"),
                            ("engineering", "Engineering"),
                            ("environment", "Environment"),
                            ("finance", "Finance"),
                            ("food-beverages", "Food & Beverages"),
                            ("healthcare", "Healthcare"),
                            ("hospitality", "Hospitality"),
                            ("information-technology", "Information Technology"),
                            ("internet", "Internet"),
                            ("legal", "Legal"),
                            ("logistics", "Logistics"),
                            ("manufacturing", "Manufacturing"),
                            ("media", "Media"),
                            ("mining", "Mining"),
                            ("music", "Music"),
                            ("pharmaceuticals", "Pharmaceuticals"),
                            ("public-administration", "Public Administration"),
                            ("real-estate", "Real Estate"),
                            ("recreation", "Recreation"),
                            ("retail", "Retail"),
                            ("science", "Science"),
                            ("services", "Services"),
                            ("technology", "Technology"),
                            ("telecommunications", "Telecommunications"),
                            ("textiles", "Textiles"),
                            ("transportation", "Transportation"),
                            ("travel", "Travel"),
                        ],
                        default="agriculture",
                        max_length=50,
                    ),
                ),
                (
                    "interests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("business-development", "Business Development"),
                                ("collaboration", "Collaboration"),
                                ("contracting-services", "Contracting Services"),
                                ("distribution", "Distribution"),
                                ("equity-investment", "Equity Investment"),
                                ("franchising", "Franchising"),
                                ("joint-venture", "Joint Venture"),
                                ("licensing", "Licensing"),
                                ("mergers-acquisitions", "Mergers & Acquisitions"),
                                ("outsourcing", "Outsourcing"),
                                ("product-development", "Product Development"),
                                ("research-development", "Research & Development"),
                                ("sales-marketing", "Sales & Marketing"),
                                ("sponsorship", "Sponsorship"),
                                ("strategic-alliance", "Strategic Alliance"),
                                ("supply-chain", "Supply Chain"),
                                ("technology-transfer", "Technology Transfer"),
                                ("venture-capital", "Venture Capital"),
                                ("white-labeling", "White Labeling"),
                            ],
                            default="collaboration",
                            max_length=20,
                        ),
                        size=None,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
