# Generated by Django 4.0.3 on 2023-06-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_company_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sender',
            new_name='user',
        ),
    ]
