# Generated by Django 4.0.3 on 2023-06-01 23:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_profile_company_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_description",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_employees",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agriculture", "Agriculture"),
                    ("construction", "Construction"),
                    ("education", "Education"),
                    ("energy", "Energy"),
                    ("engineering", "Engineering"),
                    ("environment", "Environment"),
                    ("finance", "Finance"),
                    ("food-beverages", "Food & Beverages"),
                    ("healthcare", "Healthcare"),
                    ("hospitality", "Hospitality"),
                    ("information-technology", "Information Technology"),
                    ("internet", "Internet"),
                    ("legal", "Legal"),
                    ("logistics", "Logistics"),
                    ("manufacturing", "Manufacturing"),
                    ("media", "Media"),
                    ("mining", "Mining"),
                    ("music", "Music"),
                    ("pharmaceuticals", "Pharmaceuticals"),
                    ("public-administration", "Public Administration"),
                    ("real-estate", "Real Estate"),
                    ("recreation", "Recreation"),
                    ("retail", "Retail"),
                    ("science", "Science"),
                    ("services", "Services"),
                    ("technology", "Technology"),
                    ("telecommunications", "Telecommunications"),
                    ("textiles", "Textiles"),
                    ("transportation", "Transportation"),
                    ("travel", "Travel"),
                ],
                default="agriculture",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company_investment",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[("startup", "Startup"), ("corporation", "Corporation")],
                default="startup",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company_valuation",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("business-development", "Business Development"),
                        ("collaboration", "Collaboration"),
                        ("contracting-services", "Contracting Services"),
                        ("distribution", "Distribution"),
                        ("equity-investment", "Equity Investment"),
                        ("franchising", "Franchising"),
                        ("joint-venture", "Joint Venture"),
                        ("licensing", "Licensing"),
                        ("mergers-acquisitions", "Mergers & Acquisitions"),
                        ("outsourcing", "Outsourcing"),
                        ("product-development", "Product Development"),
                        ("research-development", "Research & Development"),
                        ("sales-marketing", "Sales & Marketing"),
                        ("sponsorship", "Sponsorship"),
                        ("strategic-alliance", "Strategic Alliance"),
                        ("supply-chain", "Supply Chain"),
                        ("technology-transfer", "Technology Transfer"),
                        ("venture-capital", "Venture Capital"),
                        ("white-labeling", "White Labeling"),
                    ],
                    default="collaboration",
                    max_length=50,
                    null=True,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="meeting_link",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
