# Generated by Django 4.0.3 on 2023-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_company_description_user_company_employees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="interest",
            field=models.CharField(
                choices=[
                    ("business-development", "Business Development"),
                    ("collaboration", "Collaboration"),
                    ("contracting-services", "Contracting Services"),
                    ("distribution", "Distribution"),
                    ("equity-investment", "Equity Investment"),
                    ("franchising", "Franchising"),
                    ("joint-venture", "Joint Venture"),
                    ("licensing", "Licensing"),
                    ("mergers-acquisitions", "Mergers & Acquisitions"),
                    ("outsourcing", "Outsourcing"),
                    ("product-development", "Product Development"),
                    ("research-development", "Research & Development"),
                    ("sales-marketing", "Sales & Marketing"),
                    ("sponsorship", "Sponsorship"),
                    ("strategic-alliance", "Strategic Alliance"),
                    ("supply-chain", "Supply Chain"),
                    ("technology-transfer", "Technology Transfer"),
                    ("venture-capital", "Venture Capital"),
                    ("white-labeling", "White Labeling"),
                ],
                default="collaboration",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="message",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
