# Generated by Django 4.0.3 on 2023-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invitation_sent_at_user_has_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
