export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL';

export const ADD_PHOTO_REQUEST = 'ADD_PHOTO_REQUEST';
export const ADD_PHOTO_SUCCESS = 'ADD_PHOTO_SUCCESS';
export const ADD_PHOTO_FAIL = 'ADD_PHOTO_FAIL';

export const LIST_MEMBERS_REQUEST = 'LIST_MEMBERS_REQUEST';
export const LIST_MEMBERS_SUCCESS = 'LIST_MEMBERS_SUCCESS';
export const LIST_MEMBERS_FAIL = 'LIST_MEMBERS_FAIL';

export const GET_MEMBER_REQUEST = 'GET_MEMBER_REQUEST';
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS';
export const GET_MEMBER_FAIL = 'GET_MEMBER_FAIL';

export const APPROVE_MEMBER_REQUEST = 'APPROVE_MEMBER_REQUEST';
export const APPROVE_MEMBER_SUCCESS = 'APPROVE_MEMBER_SUCCESS';
export const APPROVE_MEMBER_FAIL = 'APPROVE_MEMBER_FAIL';

export const DISAPPROVE_MEMBER_REQUEST = 'DISAPPROVE_MEMBER_REQUEST';
export const DISAPPROVE_MEMBER_SUCCESS = 'DISAPPROVE_MEMBER_SUCCESS';
export const DISAPPROVE_MEMBER_FAIL = 'DISAPPROVE_MEMBER_FAIL';

export const CREATE_PROP_REQUEST = 'CREATE_PROP_REQUEST';
export const CREATE_PROP_SUCCESS = 'CREATE_PROP_SUCCESS';
export const CREATE_PROP_FAIL = 'CREATE_PROP_FAIL';

export const LIST_PROP_REQUEST = 'LIST_PROP_REQUEST';
export const LIST_PROP_SUCCESS = 'LIST_PROP_SUCCESS';
export const LIST_PROP_FAIL = 'LIST_PROP_FAIL';

export const GET_PROP_REQUEST = 'GET_PROP_REQUEST';
export const GET_PROP_SUCCESS = 'GET_PROP_SUCCESS';
export const GET_PROP_FAIL = 'GET_PROP_FAIL';

export const POSITIVE_PROP_REQUEST = 'POSITIVE_PROP_REQUEST';
export const POSITIVE_PROP_SUCCESS = 'POSITIVE_PROP_SUCCESS';
export const POSITIVE_PROP_FAIL = 'POSITIVE_PROP_FAIL';

export const NEGATIVE_PROP_REQUEST = 'NEGATIVE_PROP_REQUEST';
export const NEGATIVE_PROP_SUCCESS = 'NEGATIVE_PROP_SUCCESS';
export const NEGATIVE_PROP_FAIL = 'NEGATIVE_PROP_FAIL';
